import type { ComponentType } from "react"
import {
  Home,
  ChefHat,
  Bath,
  TreePine,
  Sparkles,
  HomeIcon as House,
  Building,
  Building2,
  LayoutGrid,
  Castle,
  Mountain,
  Sprout,
  Expand,
  Armchair,
  UtensilsCrossed,
  Sun,
  BedDouble,
  Waves,
  Flame,
  Cloud,
  Car,
  DoorOpen,
  Landmark,
  Laptop,
  Wine,
  Film,
  Dumbbell,
  Gamepad2,
  Baby,
} from "lucide-react"

const BuildingOutline = Building

const CATEGORY_ICON_MAP: Record<string, ComponentType<{ className?: string }>> = {
  house: Home,
  "kitchen-living": ChefHat,
  "bed-bath": Bath,
  outdoor: TreePine,
  other: Sparkles,
  residential: House,
  commercial: Building,
  renovation: BuildingOutline,
  "new-construction": Building2,
}

const DEFAULT_CATEGORY_ICON = LayoutGrid

export const SUBTYPE_ICON_MAP: Record<string, ComponentType<{ className?: string }>> = {
  "house-villa": Castle,
  "house-house": Home,
  "house-apartment": Building2,
  "house-chalet": Mountain,
  "house-bungalow": House,
  "house-farm": Sprout,
  "house-extension": Expand,
  "kitchen-living-kitchen": ChefHat,
  "kitchen-living-living-room": Armchair,
  "kitchen-living-dining-room": UtensilsCrossed,
  "kitchen-living-sunroom": Sun,
  "bed-bath-bathroom": Bath,
  "bed-bath-bedroom": BedDouble,
  "bed-bath-indoor-pool": Waves,
  "bed-bath-jacuzzi": Waves,
  "bed-bath-sauna": Flame,
  "bed-bath-steam-room": Cloud,
  "outdoor-garden": TreePine,
  "outdoor-outdoor-pool": Waves,
  "outdoor-garden-house": House,
  "outdoor-outdoor-kitchen": UtensilsCrossed,
  "outdoor-garage": Car,
  "outdoor-porch": DoorOpen,
  "other-hall": Landmark,
  "other-home-office": Laptop,
  "other-bar": Wine,
  "other-cinema": Film,
  "other-gym": Dumbbell,
  "other-game-room": Gamepad2,
  "other-kids-room": Baby,
  "other-wine-cellar": Wine,
}
