export const csvData = {
  features: [
    "Metal constructions",
    "Stucco walls",
    "Glass facades",
    "Slate roof",
    "Bamboo",
    "Natural Stone",
    "Exposed brick",
    "Reclaimed wood",
    "Thatched roof",
    "Exposed concrete",
    "Solar panels",
    "Green roof",
    "Smart home technology",
    "Underfloor heating",
    "Heat pump",
    "Insulation",
    "Double glazing",
    "Ventilation system",
  ],

  featureCategories: ["Structural", "Exterior", "Interior", "Sustainable", "Technology", "Comfort", "Safety"],

  listingTypes: [
    "Warehouse",
    "Office Building",
    "Retail Space",
    "Industrial Facility",
    "Mixed-Use Development",
    "Residential Complex",
    "Commercial Plaza",
    "Manufacturing Plant",
    "Distribution Center",
    "Business Park",
  ],

  projectAttributes: [
    "Building Year",
    "Total Area",
    "Number of Floors",
    "Parking Spaces",
    "Energy Rating",
    "Accessibility Features",
    "Zoning Classification",
    "Construction Type",
    "Occupancy Type",
    "Fire Safety Rating",
  ],

  professionalCategories: [
    "Architect",
    "Interior Designer",
    "Contractor",
    "Engineer",
    "Landscape Architect",
    "Project Manager",
    "Consultant",
    "Specialist",
    "Surveyor",
    "Planning Consultant",
  ],
}

export const projectStyles = [
  "Modern",
  "Contemporary",
  "Traditional",
  "Minimalist",
  "Industrial",
  "Scandinavian",
  "Mediterranean",
  "Rustic",
  "Mid-Century Modern",
  "Bohemian",
  "Coastal",
  "Farmhouse",
  "Transitional",
  "Urban Modern",
  "Eclectic",
]

export const locationFeatures = [
  "Lakefront",
  "Amazing views",
  "City view",
  "Countryside",
  "Golfing",
  "Ski resort",
  "Waterfront",
  "Beach",
  "Coastal",
  "Forest",
  "Mountains",
  "Urban center",
  "Suburban",
  "Historic district",
  "Business district",
]

export const buildingTypesByCategory = {
  Houses: [
    "Villa",
    "House",
    "Townhouse",
    "Cottage",
    "Farmhouse",
    "Mansion",
    "Ranch",
    "Detached House",
    "Semi-Detached House",
    "Tiny House",
    "Modular Home",
    "Row House",
    "Manufactured Home",
    "Cabin",
    "Chalet",
    "Bungalow",
    "Extension",
  ],
  Apartments: ["Apartment", "Penthouse", "Duplex", "Loft", "Studio", "Co-op"],
  Commercial: [
    "Commercial Building",
    "Office Space",
    "Retail Space",
    "Industrial Space",
    "Mixed-Use Building",
    "Warehouse",
  ],
  Specialty: ["Floating House", "Houseboat"],
}

// Named exports for backward compatibility
export const LISTING_TYPES = csvData.listingTypes
export const FEATURES = csvData.features
